name: 'Create an product page'
author: 'Open Catalogi'
description: 'Creates an product page for an given repository'

branding:
  icon: 'file-plus'
  color: 'blue'

inputs:
  remoterepo:
    description: 'Git url of the remote repository you want to check'
    required: false
    default: ''
  publiccode:
    description: 'publiccode.yml path'
    required: false
    default: 'publiccode.yml'
  gitname:
    description: 'Git name configuration for bump commit'
    required: false
    default: 'Open Catalogi bot'
  gitmail:
    description: 'Git mail configuration for bump commit'
    required: false
    default: 'bot@opencatalogi.nl'

outputs:
  version:
    description: 'New version of softwareVersion field in publiccode.yml'
  releaseDate:
    description: 'New release date of releaseDate field in publiccode.yml'

runs:
  using: "composite"
  steps:
    - name: Get the Product Website Template Code
      uses: actions/checkout@v2
      with:
        repository: ConductionNL/product-website-template
        ref: development

    # With special thanxs to https://github.com/SpicyPizza/create-envfile
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
        envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
        envkey_GATSBY_GITHUB_API_BASE_URL: ${{ env.GITHUB_API_BASE_URL }}
        envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
        envkey_GATSBY_NAVBAR_LOGO_URL: ${{ env.NAVBAR_LOGO_URL }}
        envkey_GATSBY_GITHUB_DOCS_DIRECTORY_PATHS: ${{ env.GITHUB_DOCS_DIRECTORY_PATHS }}
        envkey_GATSBY_READ_THE_DOCS_URL: ${{ env.READ_THE_DOCS_URL }}
        envkey_GATSBY_SLACK_URL: ${{ env.SLACK_URL }}
        envkey_GATSBY_GITHUB_REPOSITORY_URL: ${{ env.GITHUB_REPOSITORY_URL }}
        envkey_GATSBY_JUMBOTRON_TITLE: ${{ env.JUMBOTRON_TITLE }}
        envkey_GATSBY_JUMBOTRON_SUBTITLE: ${{ env.JUMBOTRON_SUBTITLE }}
        envkey_GATSBY_JUMBOTRON_DESCRIPTION: ${{ env.JUMBOTRON_DESCRIPTION }}
        envkey_GATSBY_JUMBOTRON_SVG: ${{ env.JUMBOTRON_SVG }}
        envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
        envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
        envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
        directory: pwa/static
        file_name: .env.production
        fail_on_empty: true
        sort_keys: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: cd pwa && npm install

    - name: Remove old Gatsby cache
      run: rm -rf pwa/.cache

    - name: Build application
      run: cd pwa && npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: ${{ env.GITHUB_PAGES_BRANCH }}
        folder: pwa/public

