name: My Open Catalogi Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update publiccode.yaml
        uses: OpenCatalogi/publiccode-action@1.1.1